spring:
  mysql:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bugtracker?autoReconnect=true
    username: mantisbt
    password: mantisbt

  jpa:
    hibernate: # hibernate
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate: # hibernate property
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org:
#      springframework: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 8088
